version: "3.9"

services:
  proxy:
    image: nginx:1.24-alpine
    working_dir: /etc/nginx
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api
      - web
    networks:
      - backend
      - frontend
    ports:
      - "443:443"

  api:
    build:
      context: api
    command: sh -c "go mod vendor && air"
    volumes:
      - ./api:/app
    depends_on:
      - database
    networks:
      - backend

  web:
    build:
      context: web
    command: sh -c "pnpm i && pnpm dev --host 0.0.0.0 --port 8080"
    tty: true
    user: node
    volumes:
      - ./web:/home/node/app
    networks:
      - frontend

  database:
    image: percona:8.0-centos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobs
    ports:
      - "3307:3306"
    networks:
      - backend

networks:
  backend:
  frontend:
