up:
	docker-compose up -d

down:
	docker-compose down

logs:
	docker-compose logs -f api

sh:
	docker-compose exec api sh

lint:
	docker-compose exec api dotnet format JobSearch.sln --verbosity detailed
