name: "Api"

on:
  push:
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - run: go mod verify
      - run: golint .
      - run: go vet .
      - run: go fmt .
      - run: go test -v
      - run: go build -v .
